manifest:
  remotes:
    - name: rafaelromao
      url-base: https://github.com/rafaelromao/zmk
  projects:
    - name: zmk
      remote: zmk
      revision: 20240328/rafaelromao/main
      import: app/west.yml
  self:
    path: config