manifest:
  remotes:
    - name: caksoylar
      url-base: https://github.com/caksoylar
  projects:
    - name: zmk
      remote: caksoylar
      revision: https://github.com/caksoylar/zmk/commits/caksoylar/zen-v2
      import: app/west.yml
  self:
    path: config
